version: 2
defaults: &defaults
  docker:
    # Same image for building weaveworks/weave
    - image: golang:1.10.1-stretch
  working_directory: /go/src/github.com/weaveworks/go-odp
jobs:
  unit-test:
    <<: *defaults
    steps:
      - checkout
      - run: go test ./...
  build:
    <<: *defaults
    steps:
      - checkout
      - run: go build -o odp-cmd ./tool/odp
workflows:
  version: 2
  build_test:
    jobs:
      - unit-test
      - build
